// Array producto "Bibliotecas"
const bibliotecas =[
    {
        id:1,
        nombre: "Doble Negra",
        descripcion: "Biblioteca doble negra. Hecha para guardar libros y mantener el diseño interior.",
        color: "Negro",
        precio: 25000,
        stock: 1,
    },
    {
        id:2,
        nombre: "Modular Blanca",
        descripcion: "Biblioteca sofisticada blanca. Diseño disrruptivo en el armado de muebles.",
        color: "Blanco",
        precio: 28000,
        stock: 5,
    },
    {
        id:3,
        nombre: "Triple Blanca",
        descripcion: "Biblioteca blanca modular triple con diseño de vanguardia y sofisticación.",
        color: "Blanco",
        precio: 36000,
        stock: 20,
    },
    {
        id:4,
        nombre: "Marrón Simple",
        descripcion: "Biblioteca marrón alta con puertas. Diseño para almacenar libros y adornos del hogar.",
        color: "Marrón",
        precio: 22000,
        stock: 27,
    },
    {
        id:5,
        nombre: "Blanca Simple",
        descripcion: "Biblioteca blanca simple con puertas y estantes en diseño cruzado.",
        color: "Blanco",
        precio: 18500,
        stock: 0,
    },
    {
        id:6,
        nombre: "de Madera",
        descripcion: "Biblioteca simple de madera color marrón oscuro con cuatro estantes rígidos.",
        color: "Negro",
        precio: 18000,
        stock: 14,
    },
    {
        id:7,
        nombre: "Blanca Living",
        descripcion: "Biblioteca blanca de living con estantes rellenos y cruzados. Detalles en colores claros.",
        color: "Blanco",
        precio: 29500,
        stock: 11,
    },
    {
        id:8,
        nombre: "Negra Living",
        descripcion: "Biblioteca blanca de living con estantes rellenos y cruzados. Detalles en colores oscuros..",
        color: "Negro",
        precio: 29500,
        stock: 10,
    },
    {
        id:9,
        nombre: "con Puertas",
        descripcion: "Biblioteca grande con tres puertas en color negro. Ideal para livings ámplios..",
        color: "Negro",
        precio: 41500,
        stock: 8,
    },
]

// Array producto "Mesas"
const mesas =[
    {
        id:1,
        nombre: "Mesa de Living Altura",
        descripcion: "Mesa ratona para living en color negro. Incluye mesa en color blanca para altura.",
        color: "Negro",
        precio: 21000,
        stock: 2,
    },
    {
        id:2,
        nombre: "Mesa Comerdor Elegante",
        descripcion: "Mesa de comedor en color negro. Ideal para ocho comensales en ambientes grandes.",
        color: "Negro",
        precio: 39000,
        stock: 16,
    },
    {
        id:3,
        nombre: "Mesa Cocina Metal",
        descripcion: "Mesa de material metalico en color marrón. Ideal para cocinas y ambientes pequeños.",
        color: "Negro",
        precio: 25000,
        stock: 11,
    },
    {
        id:4,
        nombre: "Mesa Comedor Madera",
        descripcion: "Mesa de living de madera de roble color marrón barnizada. Tamaño ideal apra ocho comensales.",
        color: "Marrón",
        precio: 48000,
        stock: 4,
    },
    {
        id:5,
        nombre: "Mesa Comedor Estilo",
        descripcion: "Mesa de comedor color negro con detalles en marrón. Insispensable en ambientes sofisticados.",
        color: "Negro",
        precio: 35000,
        stock: 21,
    },
    {
        id:6,
        nombre: "Mesa Comedor Rústica",
        descripcion: "Mesa de madera grande con molduras y sostenes de hierro. Ideal para ambientes rupestres.",
        color: "Marrón",
        precio: 34000,
        stock: 12,
    },
    {
        id:7,
        nombre: "Mesa Exterior",
        descripcion: "Mesa diseñada para ambientes exteriores y jardines. Ideal apra relajarse en familia.",
        color: "Marrón",
        precio: 16000,
        stock: 8,
    },
    {
        id:8,
        nombre: "Mesa Madera Metal",
        descripcion: "Mesa de madera combinada con molduras de metal. Ideal apra ambientes pequeños.",
        color: "Blanco",
        precio: 23500,
        stock: 14,
    },
    {
        id:9,
        nombre: "Mesa Madera Blanca",
        descripcion: "Mesa de madera blanca robusta con finas terminaciones en colores claros.",
        color: "Blanco",
        precio: 28500,
        stock: 9,
    },
]

// Array producto "Sillas"
const sillas =[
    {
        id:1,
        nombre: "Silla Básica",
        descripcion: "Silla blanca con terminaciones de madera. Ideal para ambientes pequeños.",
        color: "Blanco",
        precio: 10000,
        stock: 2,
    },
    {
        id:2,
        nombre: "Silla Comedor",
        descripcion: "Silla de comedor con respaldo y asiento acolchado. Diseño para comedores.",
        color: "Blanco",
        precio: 22000,
        stock: 17,
    },
    {
        id:3,
        nombre: "Silla Simple",
        descripcion: "Silla básica de comedor. Ideal para ambientes pequeños sin diseños particulares.",
        color: "Blanco",
        precio: 13500,
        stock: 11,
    },
    {
        id:4,
        nombre: "Silla de Autor",
        descripcion: "Silla fabricada de autor 'Pierre Antoine Sillene'. Pieza que combina diseño y estética.",
        color: "Blanco",
        precio: 27000,
        stock: 18,
    },
    {
        id:5,
        nombre: "Silla Pequeña",
        descripcion: "Silla pequeña para ambientes acogedores. Ideal para mesa de comedor de cuatro comensales.",
        color: "Blanco",
        precio: 7500,
        stock: 49,
    },
    {
        id:6,
        nombre: "Silla de Pana",
        descripcion: "Silla hecha con revestimiento de pana blanca. Ideal para ambientes sofisticados y modernos.",
        color: "Blanco",
        precio: 38000,
        stock: 4,
    },
    {
        id:7,
        nombre: "Silla de Mimbre",
        descripcion: "Silla de mimbre con diseño particular hecha para ambientes rupestres, con estilo y presencia.",
        color: "Marrón",
        precio: 18000,
        stock: 28,
    },
    {
        id:8,
        nombre: "Silla de Arco",
        descripcion: "Silla de estilo clásica reversionada para comedores y livings modernos. Color marrón claro.",
        color: "Marrón",
        precio: 21000,
        stock: 1,
    },
    {
        id:9,
        nombre: "Silla de Pana Marrón",
        descripcion: "Silla hecha con revestimiento de pana marrón. Ideal para ambientes sofisticados y modernos.",
        color: "Gris",
        precio: 35000,
        stock: 9,
    },
]

// Array producto "Sillones"
const sillones =[
    {
        id:1,
        nombre: "Sillón Doble",
        descripcion: "Biblioteca doble negra. Hecha para guardar libros y mantener el diseño interior.",
        color: "Blanco",
        precio: 125000,
        stock: 2,
    },
    {
        id:2,
        nombre: "Sillón de Tela",
        descripcion: "Sillón de tela de estilo clásico. Disponible en color negro y verde claro.",
        color: "Gris y Verde",
        precio: 28000,
        stock: 4,
    },
    {
        id:3,
        nombre: "Sillón Eco Cuero",
        descripcion: "Sillón hecho con material de eco cuero. Opción ideal para el ambiente de estar.",
        color: "Negro",
        precio: 62000,
        stock: 9,
    },
    {
        id:4,
        nombre: "Sillón 'Le Confort'",
        descripcion: "Sillón de autor de 'Auguste Orphane'. Diseño, estética y confort, todo en uno.",
        color: "Negro",
        precio: 72500,
        stock: 1,
    },
    {
        id:5,
        nombre: "Sillón Herradura",
        descripcion: "Sillón con forma de herradura en color blanco. Ideal apra ambientes grandes.",
        color: "Blanco",
        precio: 22000,
        stock: 6,
    },
    {
        id:6,
        nombre: "Sillón Confort",
        descripcion: "Sillón de diseño ideal para el descanso y confort. Se adapta a cualquier ambiente del hogar.",
        color: "Negro",
        precio: 150000,
        stock: 4,
    },
    {
        id:7,
        nombre: "Sillón Esquinero",
        descripcion: "Sillón esquinero en color gris de tela reforzada. Excelente opción para ambientes grandes.",
        color: "Gris",
        precio: 98000,
        stock: 7,
    },
    {
        id:8,
        nombre: "Sillón con Apoyador",
        descripcion: "Sillón con apoyador estilo cuadrillé, ideal para diseños modernos y sofisticados.",
        color: "Cuadrillé",
        precio: 55000,
        stock: 30,
    },
    {
        id:9,
        nombre: "Sillón Pastel",
        descripcion: "Sillón básico de estilo clásico. Se adapta a cualquier living de todas las casas.",
        color: "Pastel",
        precio: 35000,
        stock: 25,
    },
]